AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate deployment for Barbershop backend

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select your VPC ID

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select 2 subnets (public or private)

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group with port 5000 open

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: barbershop-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskExecutionRole-barbershop
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/barbershop
      RetentionInDays: 3

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [FARGATE]
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: barber-app
          Image: 
          PortMappings:
            - ContainerPort: 5000
          Environment:
            - Name: DB_HOST
              Value: 
            - Name: DB_USER
              Value: 
            - Name: DB_PASS
              Value: 
            - Name: DB_NAME
              Value: barbershop
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/barbershop
              awslogs-region: ap-south-1
              awslogs-stream-prefix: ecs

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: barbershop-service
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref SecurityGroupId

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
  ServiceName:
    Description: ECS Service Name
    Value: !Ref ECSService
